bump `curve25519-dalek` to 4.1.3
`cargo audit` detected a timing vulnerability in version 4.1.1

```
$ cargo audit
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
      Loaded 700 security advisories (from /Users/phil/.cargo/advisory-db)
    Updating crates.io index
    Scanning Cargo.lock for vulnerabilities (54 crate dependencies)
Crate:     curve25519-dalek
Version:   4.1.1
Title:     Timing variability in `curve25519-dalek`'s `Scalar29::sub`/`Scalar52::sub`
Date:      2024-06-18
ID:        RUSTSEC-2024-0344
URL:       https://rustsec.org/advisories/RUSTSEC-2024-0344
Solution:  Upgrade to >=4.1.3
Dependency tree:
curve25519-dalek 4.1.1
└── ed25519-dalek 2.0.0
    └── libsignify 0.6.0
        └── signify 0.6.0

error: 1 vulnerability found!
```